/**
 * @file main.c
 * @brief Main program body for the Rotation Wheel Inverted Pendulum (RWIP) STM32 project.
 * @author <Your Name>
 * @date 2023
 *
 * This file contains the main entry point and core logic for the RWIP system.
 * It initializes peripherals, sets up control modules, and runs the main control loop.
 */

#include "main.h"
#include <stdio.h>
#include <stdbool.h>
#include "trajectory_ctrl.h"
#include "encoder_speed_pos_fdbk.h"
#include "Control/regulator.h"
#include "Control/encoder.h"
#include "Control/error_handling.h"
#include "Interface/display.h"
#include "Interface/led.h"

/**
 * @defgroup RWIP_Main RWIP Main Application
 * @{
 */

// --- Constants and Macros ---
#define M2_PULSE_NBR ((4 * (M2_ENCODER_PPR)) - 1)
#define PRE_STABILIZE_LIMIT 105.0f
#define POST_STABILIZE_LIMIT 255.0f
#define UART_TIMEOUT 10
#define KR_0 635.8617f
#define KR_1 68.5572f
#define KR_2 1.5f
#define NEUTRAL_ANGLE 180.0f
#define INIT_DELAY_MS 2000

// --- Global Variables ---
ADC_HandleTypeDef hadc1;
ADC_HandleTypeDef hadc2;
CORDIC_HandleTypeDef hcordic;
TIM_HandleTypeDef htim1;
TIM_HandleTypeDef htim3;
TIM_HandleTypeDef htim4;
UART_HandleTypeDef huart2;
DMA_HandleTypeDef hdma_usart2_rx;
DMA_HandleTypeDef hdma_usart2_tx;

/**
 * @brief Regulator instance for control logic.
 */
Regulator regulator;
/**
 * @brief Encoder instance for sensor feedback.
 */
volatile Encoder encoder;
/**
 * @brief Error handling instance.
 */
ErrorHandling errorHandling;
/**
 * @brief LED interface instance.
 */
Led led;

// --- Control and State Variables ---
static float Kr[3] = {KR_0, KR_1, KR_2};
static float neutral_angle = NEUTRAL_ANGLE;
static float angle2 = 0.0f;
static int speed_var = 0;
static int delay_var = 0;
static float g_pendulum_velocity = 0.0f;
static int tickdiff = 0;
static int start_stabilization = 0;
static int swing_level = 0;
volatile float controlSignalRPM = 0.0f;
static int level = 0;
static bool stop_algo1 = false;
static bool stop_algo2 = false;
static bool stop_both_algos = false;

// --- Function Prototypes ---
static void RWIP_Init(void);
static void RWIP_MainLoop(void);
static void RWIP_InitPeripherals(void);
static void RWIP_InitModules(void);

// --- Utility Functions ---
/**
 * @brief Retarget printf to UART2.
 */
int _write(int file, char *ptr, int len)
{
    HAL_UART_Transmit(&huart2, (uint8_t *)ptr, len, UART_TIMEOUT);
    return len;
}

/**
 * @brief Initialize all peripherals and modules for RWIP.
 */
static void RWIP_Init(void)
{
    HAL_Init();
    SystemClock_Config();
    RWIP_InitPeripherals();
    MX_NVIC_Init();
    RWIP_InitModules();
    HAL_Delay(INIT_DELAY_MS);
    printf("Aligned\r\n");
}

/**
 * @brief Initialize all hardware peripherals.
 */
static void RWIP_InitPeripherals(void)
{
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_ADC1_Init();
    MX_ADC2_Init();
    MX_CORDIC_Init();
    MX_TIM1_Init();
    MX_TIM3_Init();
    MX_USART2_UART_Init();
    MX_MotorControl_Init();
    MX_TIM4_Init();
}

/**
 * @brief Initialize all software modules and control structures.
 */
static void RWIP_InitModules(void)
{
    extern MCI_Handle_t *pMCI[NBR_OF_MOTORS];
    MCI_Handle_t *motor_instance = pMCI[M1];
    (void)motor_instance; // Prevent unused warning if not used
    initRegulator(&regulator);
    initEncoder((Encoder *)&encoder);
    initErrorHandling(&errorHandling);
    initLed(&led);
    MC_StartMotor1();
    MC_ProgramSpeedRampMotor1(0, 0);
}

/**
 * @brief Main control loop for the RWIP system.
 */
static void RWIP_MainLoop(void)
{
    int trig = 0;
    while (1)
    {
        encoder.pendulum_velocity = encoder.calculatePendulumVelocity();
        encoder.pendulum_acceleration = encoder.calculatePendulumAcceleration();
        if ((angle2 > PRE_STABILIZE_LIMIT) && (angle2 < POST_STABILIZE_LIMIT))
        {
            if (trig == 0)
            {
                printf("Computing stabilize algorithm...\r\n");
                printf("encoder.pendulum_angle = %f\r\n", encoder.pendulum_angle);
                fflush(stdout);
                trig = 1;
            }
            regulator.computeStabilization();
            start_stabilization = 1;
        }
        else
        {
            start_stabilization = 0;
            regulator.computeSwingUp();
        }
    }
}

/**
 * @brief Main entry point.
 * @retval int
 */
int main(void)
{
    RWIP_Init();
    RWIP_MainLoop();
    // Should never reach here
    return 0;
}

/**
 * @}
 */

// --- Peripheral and Error Handler Implementations ---
// (Leave these as generated by STM32CubeMX, but add Doxygen comments if needed)
// ...
// (No changes to SystemClock_Config, MX_NVIC_Init, MX_ADC1_Init, etc.)
// ...
